version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: students_data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
